name: Terraform CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0  # apne version ke hisaab se change kar sakte ho

      # Step 3: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 4: Validate Terraform code
      - name: Terraform Validate
        run: terraform validate

      # Step 5: Plan infrastructure changes
      - name: Terraform Plan
        run: terraform plan

      # Step 6: (Optional) Apply changes automatically on push
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve

      - name: Check Terraform Version
        run: terraform -version

      - name: List files
        run: ls -R

